add_library(qi_ui STATIC
    BoundingBoxWidget.cpp
    BoundingBoxWidget.hpp
    ExperimentTab.cpp
    ExperimentTab.hpp
    MainWindow.cpp
    MainWindow.hpp
    MainWindow.ui
    OrbitalCamera.cpp
    OrbitalCamera.hpp
    QuadricParamsWidget.cpp
    QuadricParamsWidget.hpp
    ResultsTab.cpp
    ResultsTab.hpp
    SurfaceEditorWidget.cpp
    SurfaceEditorWidget.hpp
    TransformWidget.cpp
    TransformWidget.hpp
    TriangulationParamsWidget.cpp
    TriangulationParamsWidget.hpp
    ViewTab.cpp
    ViewTab.hpp
    Viewport3D.cpp
    Viewport3D.hpp
    version.cpp
    version.hpp
)
target_include_directories(qi_ui PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(qi_ui
    PUBLIC
        Qt6::Widgets
        Qt6::OpenGLWidgets
        Qt6::Concurrent
        Qt6::Sql
        qi_geometry
        qi_experiment
        qi_storage
)
